### ISSUE TITLE
At mention someone removes the text

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#112] opened 2019-08-09 10:33 UTC
![BubRPhDfft](https://user-images.githubusercontent.com/29014463/62773173-255ecb00-babf-11e9-8da1-8a401508cf2f.gif)

**Comment by atapas** [comment] 2019-08-15 11:36
This is an irritating one..

**Comment by minecrawler** [comment] 2019-08-15 12:57
duplicate of #41

**Closed** 2020-01-15 12:59 UTC
Labels: bug
