### ISSUE TITLE
New features menu on Android

### ISSUE THREAD

**Issue by EmilMoe** [Hashnode/user-feedback#64] opened 2019-04-25 07:56 UTC
**Describe the bug**
There's an error with the mobile app and the new features menu
It's only open on above the window

**To Reproduce**
Open mobile app, open new features menu (Android)

**Expected behavior**
Menu isn't visible

**Screenshots**
![image](https://user-images.githubusercontent.com/555083/56719106-5a2d5900-6740-11e9-98b7-19ea306531bf.png)

**Desktop (please complete the following information):**
No

**Smartphone (please complete the following information):**
 Android, Honor 8

**Additional context**
N/A

**Comment by BolajiAyodeji** [comment] 2020-01-15 15:34
Hi @EmilMoe, thanks for reporting.

Can you provide some additional context as I couldn't reproduce this error? I'll be closing this, for now, please re-open.

**Closed by BolajiAyodeji** 2020-01-15 15:34 UTC
Labels: bug

**Comment by EmilMoe** [comment] 2020-01-15 16:47
I Thybo you changed something soccer I opened this nearly a year ago, so not sure where it is now

**Comment by BolajiAyodeji** [comment] 2020-01-15 17:32
Probably. Please note that the Android app is a WIP, we'll update you when we have a stable version. For now, please keep sending your feedbacks.
