### ISSUE TITLE
Comments were not displaying

### ISSUE THREAD

**Issue by sivabalan02** [Hashnode/user-feedback#154] opened 2020-01-30 06:21 UTC
**Describe the bug**
If i click the post on the notifications, its redirect to the post page. Its show the comments count. But not displaying any comments. I have to reload the page to view the comments 

**To Reproduce**
1. Go to Notifications
2. Click on any post
3. Post will shown and with the total comment counts
4. No comments will be displayed

**Expected behavior**

**Screenshots**
![Screenshot from 2020-01-30 11-53-45](https://user-images.githubusercontent.com/13597538/73425284-30e8cb80-4357-11ea-8543-93dda06ed486.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Firefox
 - Version 72.0

**Comment by BolajiAyodeji** [comment] 2020-01-31 14:06
Hi @sivabalan02, thanks for reporting this.

Are you still experiencing this issue? I tried reproducing this error but it seems to be working fine for me. Let me know, please.

**Comment by sivabalan02** [comment] 2020-02-03 12:26
Yes. Today also i faced the same issue

**Comment by BolajiAyodeji** [comment] 2020-04-04 05:31
Hi @sivabalan02, this issue is fixed now. Thanks for your patience.
Do let me know if you need any more help.

**Closed by BolajiAyodeji** 2020-04-04 05:31 UTC
Labels: bug, no-issue-activity, reviewed
